*** Settings ***
Library   ../../../../../py_sources/logigear/setup.py        
Library   ../../../../../py_sources/logigear/page_objects/system_manager/login/LoginPage${PLATFORM}.py
Library   ../../../../../py_sources/logigear/page_objects/system_manager/site_manager/SiteManagerPage${PLATFORM}.py
Library   ../../../../../py_sources/logigear/page_objects/system_manager/reports/reports/ReportsPage${PLATFORM}.py    	
Library   ../../../../../py_sources/logigear/page_objects/system_manager/tools/database_tools/RestoreDatabasePage${PLATFORM}.py
Library   ../../../../../py_sources/logigear/page_objects/system_manager/zone_header/ZoneHeaderPage${PLATFORM}.py    

Resource    ../../../../../resources/constants.robot

Suite Setup    Run Keywords    Open SM Login Page
    ...    AND    Login To SM    ${USERNAME}    ${PASSWORD}

Suite Teardown    Run Keywords    Select Main Menu    ${Reports}   
    ...    AND    Delete Report    ${report_name}
    ...    AND    Select Main Menu    ${Site Manager}
    ...    AND    Delete Object On Content Table    ${SITE_NODE}
    ...    AND    Close Browser

Default Tags    Reports
Force Tags    SM-29834

*** Variables ***
${CITY_NAME}    New_6xLC--Trifurcated
${CAMPUS_NAME}    New_6xLC--DM12
${CV_01_6xLCEB IBM_Circuit_3_NAME}    CV_01_6xLCEB IBM_Circuit_3
${CV_Multi_Conduit_NAME}    CV_Multi_Conduit
${CV_New_6xLC--4xLC_NAME}    CV_New_6xLC--4xLC
${CV_New_6xLC--DM08_NAME}    CV_New_6xLC--DM08
${CV_New_6xLC--New_6xLC_NAME}    CV_New_6xLC--New_6xLC
${CV_New_6xLC--Switch MPO port_NAME}    CV_New_6xLC--Switch MPO port
${BD_01_ 6xLCEB_inside_splice-splice_NAME}    BD_01_ 6xLCEB_inside_splice-splice
${BD_01_6xLCEB IBM_Circuit_3_NAME}    BD_01_6xLCEB IBM_Circuit_3
${BD_01_Multi_Conduit_NAME}    BD_01_Multi_Conduit
${BD_01_New_6xLC--New_6xLC_NAME}    BD_01_New_6xLC--New_6xLC
${BD_02_ 6xLCEB_inside_splice-splice_NAME}    BD_02_ 6xLCEB_inside_splice-splice
${BD_02_Multi_Conduit_NAME}    BD_02_Multi_Conduit
${BD_03_Multi_Conduit_NAME}    BD_03_Multi_Conduit
${BD_6xLCEB_inside_splice-panel_01_NAME}    BD_6xLCEB_inside_splice-panel_01
${BD_6xLCEB_inside_splice-panel_02_NAME}    BD_6xLCEB_inside_splice-panel_02
${BD_New_6xLC--4xLC_NAME}    BD_New_6xLC--4xLC
${BD_New_6xLC--DM08_NAME}    BD_New_6xLC--DM08
${BD_New_6xLC--Switch MPO port_NAME}    BD_New_6xLC--Switch MPO port
${CAMPUS_NAME_DEFAULT}    Campus 01
${BUILDING_NAME_DEFAULT}    Building 01
${CABLE_VAULT_NAME_DEFAULT}    Cable Vault 01
${FLOOR_NAME}    Floor 01 
${ROOM_NAME}    Room 01
${RACK_GROUP_NAME}    Rack Group 01
${RACK_NAME}    Rack 001
${RACK_NAME_2}    Rack 002
${CABINET_NAME}    Cabinet 001
${FULL_RACK_NAME}    1:1 Rack 001
${FULL_RACK_NAME_2}    1:1 Rack 002
${FULL_CABINET_NAME}    1:1 Cabinet 001
${SWITCH_NAME_1}    Switch 01
${SWITCH_NAME_2}    Switch 02
${LC_SWITCH_NAME}    LC Switch 01
${CARD_NAME_1}    Card 01
${CARD_NAME_2}    Card 02
${CARD_NAME_3}    Card 03
${CARD_NAME_4}    Card 04
${CARD_NAME_5}    Card 05
${GBIC_SLOT_1}    GBIC Slot 01
${GBIC_SLOT_2}    GBIC Slot 02
${GBIC_SLOT_3}    GBIC Slot 03
${GBIC_SLOT_4}    GBIC Slot 04
${GBIC_SLOT_5}    GBIC Slot 05
${GBIC_SLOT_6}    GBIC Slot 06
${GBIC_SLOT_9}    GBIC Slot 09
${PANEL_NAME}    Panel 01
${PANEL_NAME_2}    Panel 02
${PANEL_NAME_3}    Panel 03
${MPO_PANEL_1}    MPO Panel 01
${MPO_PANEL_2}    MPO Panel 02        
${LC_PANEL}    LC Panel 01
${MODULE_DM12}    Module 1A (DM12)
${ACTION}    Created
${STATUS_1}    Scheduled
${STATUS_2}    On Hold
${WORK_ORDER_TYPE_1}    Patching
${report_name}    Work_Order_Detail_Report   
${WO_6xLC-Switch MPO}    WO_6xLC-Switch MPO
${WO_6xLC--4xLC}    WO_6xLC--4xLC
${WO_Splice_Panel}    WO_Splice_Panel
${WO_Inside_Splice_01}    WO_Inside_Splice_01
${WO_LCEB IBM}    WO_LCEB IBM
${WO_Multiple_Conduits}    WO_Multiple_Conduits
${WO_6xLC--DM08}    WO_6xLC--DM08
${WO_6xLC--DM12}    WO_6xLC--DM12
${WO_6xLC--Trifurcated}    WO_6xLC--Trifurcated
${WO_6xLC--6xLC}    WO_6xLC--6xLC
${2020-03-27}    2020-03-27
${2050-03-27}    2050-03-27
${2020-03-30}    2020-03-30
${2020-03-26}    2020-03-26
${2050-03-25}    2050-03-25
${Placed on hold by}    Placed on hold by
${RESTORE_FILE_NAME_1}    SM_29834_Add_Patch.bak
${RESTORE_FILE_NAME_2}    SM_29834_Remove_Patch.bak

*** Test Cases ***
(Bulk-29834-01-10_WDR-01)_Verify that the "Work Order Details" report generated for add patching connection type MPO-6xLC correctly
 
    ${Task_type_1}    Set Variable    Add Patch
    ${WO_Inside_Splide_02}    Set Variable    WO_Inside_Splide_02    

    [Tags]    Sanity
    
    # 1. Restore Data from SM9.1 on the latest build
    Restore Database    ${RESTORE_FILE_NAME_1}    ${DIR_FILE_BK}
    Login To SM    ${USERNAME}    ${PASSWORD}
    
    # 2. Select Report Tab and select "Work Order Details" report.
    Select Main Menu    ${Reports}
    
    # 3. View Report and observe result
	View Report    ${report_name}
	Select Filter For Report    addMultiSelectFilter=Work Type:${WORK_ORDER_TYPE_1}    selectLocationType=Check    treeNode=${SITE_NODE}    clickViewBtn=${True}
	Sort View Report Table By Column Name    Port (1)   typeSort=desc
	Sort View Report Table By Column Name    Port (1)   
	${headers}    Set Variable    Work Order ID,Earliest Date,Latest Date,Expected Date,Task Type,Action,User Name,Technician,Job Summary,Task ID,Work Order Type,Date Created,Location (1),Campus (1),City (1),Building (1),Floor (1),Room (1),Rack Group (1),Zone (1),Rack Position (1),Rack Name (1),Equipment (1),Card (1),Module (1),Port (1),Location (2),Campus (2),City (2),Building (2),Floor (2),Room (2),Rack Group (2),Zone (2),Rack Position (2),Rack Name (2),Equipment (2),Card (2),Module (2),Port (2),Copper Port,Fiber Port,Connection ID,Service Ticket ID,Current Status
	${values_list}    Create List
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_New_6xLC--New_6xLC_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_New_6xLC--New_6xLC_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${MPO_PANEL_1},,,${01},${SITE_NODE} / ${BD_01_New_6xLC--New_6xLC_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_New_6xLC--New_6xLC_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${MPO_PANEL_1},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${01},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,7,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2020-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${1-1},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2020-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${2-2},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2020-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${3-3},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2020-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${4-4},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 1},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 1},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 1},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 1},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 2},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 2},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 2},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 2},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 3},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 3},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 3},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 3},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 4},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 4},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 4},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 4},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${05},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 5},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 5},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 5},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 5},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,New_6xLC--New_6xLC,7,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLC--DM08,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM12},${2020-03-26},${2050-03-25},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,6xLC--DM12,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${06},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 6},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 6},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splide_02},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 6},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_Multiple_Conduits},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 6},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,2,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${02},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,8,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${02},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${02},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,3,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${03},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,9,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${03},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${03},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,4,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${04},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,10,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${04},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${04},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,5,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${05},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,11,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${05},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${05},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,6,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${06},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-26},${2050-03-25},${2020-03-26},${Task_type_1},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,12,${WORK_ORDER_TYPE_1},${2020-03-26},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${06},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${06},No,Yes,,,${STATUS_1}
  		 
    ${rows_list}    Create List    1    2    3    4    5    6    7    8    9    10    11    12    13    14    15    16    17    18    19    20    21    22
    ...    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39    40    41    42    43    44    45    46    47
    ...    48    49    50    51    52    53    54    55    56    57    58    59    60    61    62    63    64    65    66    67    68    69    70    71    

    :FOR    ${i}    IN RANGE    0    len(${rows_list})    	         
	\   Check Report Data Line    ${rows_list}[${i}]    ${headers}    ${values_list}[${i}]

(Bulk-29834-01-10_WDR-02)_Verify that the "Work Order Details" report generated for remove patching connection type MPO-6xLC correctly
    
    ${Task_type_2}    Set Variable    Remove Patch
    ${WO_Inside_Splice_02}    Set Variable    WO_Inside_Splice_02 
  
    [Tags]    Sanity

    #Check Remove Patching Report.
    # 1. Restore Data from SM9.1 on the latest build
    Restore Database    ${RESTORE_FILE_NAME_2}    ${DIR_FILE_BK}
    Login To SM    ${USERNAME}    ${PASSWORD}
    
    # 2. Select Report Tab and select "Work Order Details" report.
    Select Main Menu    ${Reports}
	View Report    ${report_name}
	Select Filter For Report    addMultiSelectFilter=Work Type:${WORK_ORDER_TYPE_1}    selectLocationType=Check    treeNode=${SITE_NODE}    clickViewBtn=${True}
	Sort View Report Table By Column Name    Port (1)   typeSort=desc
	Sort View Report Table By Column Name    Port (1)
	Sort View Report Table By Column Name    Port (1)   typeSort=desc
	Sort View Report Table By Column Name    Port (1)
	${headers}    Set Variable    Work Order ID,Earliest Date,Latest Date,Expected Date,Task Type,Action,User Name,Technician,Job Summary,Task ID,Work Order Type,Date Created,Location (1),Campus (1),City (1),Building (1),Floor (1),Room (1),Rack Group (1),Zone (1),Rack Position (1),Rack Name (1),Equipment (1),Card (1),Module (1),Port (1),Location (2),Campus (2),City (2),Building (2),Floor (2),Room (2),Rack Group (2),Zone (2),Rack Position (2),Rack Name (2),Equipment (2),Card (2),Module (2),Port (2),Copper Port,Fiber Port,Connection ID,Service Ticket ID,Current Status

	${values_list}    Create List
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${01},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,7,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${1-1},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${2-2},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${3-3},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--4xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${MPO_PANEL_2},,,${01}/${4-4},${SITE_NODE} / ${CV_New_6xLC--4xLC_NAME} / ${FULL_CABINET_NAME},,,,,${CV_New_6xLC--4xLC_NAME},,1,1,${CABINET_NAME},${LC_PANEL},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Trifurcated,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 1},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Splice_Splice,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 1},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 1},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_Multiple_Conduits},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,MultipleConduits,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 1},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,SplicePanel,1,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 1},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Trifurcated,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 2},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Splice_Splice,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 2},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 2},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_Multiple_Conduits},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,MultipleConduits,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 2},${SITE_NODE} / ${CV_Multi_Conduit_NAME} / ${FULL_RACK_NAME},,,,,${CV_Multi_Conduit_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_Splice_Panel},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,SplicePanel,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 2},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 3},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--Trifurcated},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Trifurcated,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${01}/${Pair 3},${SITE_NODE} / ${CITY_NAME} / ${CAMPUS_NAME_DEFAULT} / ${BUILDING_NAME_DEFAULT} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},${CAMPUS_NAME_DEFAULT},${CITY_NAME},${BUILDING_NAME_DEFAULT},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_01},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,Splice_Splice,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_5},,${01}/${Pair 3},${SITE_NODE} / ${BD_01_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_01_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 3},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_Splice_Panel},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,SplicePanel,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 3},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 4},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 4},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_Splice_Panel},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,SplicePanel,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 4},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${05},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${05},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 5},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_2}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 5},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${05},No,Yes,,,${STATUS_2}
	...    ${WO_Splice_Panel},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,SplicePanel,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_1},,,${01}/${Pair 5},${SITE_NODE} / ${BD_6xLCEB_inside_splice-panel_01_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME},,,${BD_6xLCEB_inside_splice-panel_01_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--6xLC},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,New_6xLC--New_6xLC,6,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${MPO_PANEL_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--New_6xLC_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--New_6xLC_NAME},,1,1,${RACK_NAME},${LC_PANEL},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_6xLC--DM08},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM08,6,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--DM08_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--DM08_NAME},,1,1,${RACK_NAME},${SWITCH_NAME_2},,,${06},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC--DM12},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,6xLC--DM12,6,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CAMPUS_NAME} / ${CABLE_VAULT_NAME_DEFAULT} / ${FULL_RACK_NAME},${CAMPUS_NAME},,,,${CABLE_VAULT_NAME_DEFAULT},,1,1,${RACK_NAME},${SWITCH_NAME_2},${CARD_NAME_3},,${06},No,Yes,,,${STATUS_2}
	...    ${WO_6xLC-Switch MPO},${2020-03-30},${2020-03-30},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-30},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${01}/${Pair 6},${SITE_NODE} / ${CV_New_6xLC--Switch MPO port_NAME} / ${FULL_RACK_NAME},,,,,${CV_New_6xLC--Switch MPO port_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_2}
	...    ${WO_Inside_Splice_02},${2020-03-27},${2050-03-27},${Placed on hold by} ${USERNAME}.,${Task_type_2},${ACTION},${USERNAME},,,6,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${MPO_PANEL_1},,,${01}/${Pair 6},${SITE_NODE} / ${BD_02_ 6xLCEB_inside_splice-splice_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${FULL_RACK_NAME_2},,,${BD_02_ 6xLCEB_inside_splice-splice_NAME},${FLOOR_NAME},${ROOM_NAME},,1,1,${RACK_NAME_2},${PANEL_NAME_2},,,${06},No,Yes,,,${STATUS_2}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,2,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${02},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${02},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,8,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${02},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${02},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,3,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${03},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${03},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,9,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${03},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${03},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,4,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${04},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${04},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,10,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${04},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${04},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,5,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${05},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${05},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,11,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${05},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${05},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,6,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${SWITCH_NAME_1},${CARD_NAME_3},,${06},${SITE_NODE} / ${BD_01_6xLCEB IBM_Circuit_3_NAME} / ${FLOOR_NAME} / ${ROOM_NAME} / ${RACK_GROUP_NAME} / ${FULL_RACK_NAME},,,${BD_01_6xLCEB IBM_Circuit_3_NAME},${FLOOR_NAME},${ROOM_NAME},${RACK_GROUP_NAME},1,1,${RACK_NAME},${PANEL_NAME},,,${06},No,Yes,,,${STATUS_1}
	...    ${WO_LCEB IBM},${2020-03-27},${2050-03-27},${2020-03-27},${Task_type_2},${ACTION},${USERNAME},,6xLCEB IBM circuit 3,12,${WORK_ORDER_TYPE_1},${2020-03-27},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME_2},,,${06},${SITE_NODE} / ${CV_01_6xLCEB IBM_Circuit_3_NAME} / ${FULL_RACK_NAME},,,,,${CV_01_6xLCEB IBM_Circuit_3_NAME},,1,1,${RACK_NAME},${PANEL_NAME},,${MODULE_DM12},${06},No,Yes,,,${STATUS_1}

    ${rows_list}    Create List    1    2    3    4    5    6    7    8    9    10    11    12    13    14    15    16    17    18    19    20
    ...    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39    40
    ...    41    42    43    44    45    46    47    48    49    50    51    52    53    54    55    56    57    58    59        

    :FOR    ${i}    IN RANGE    0    len(${rows_list})    	         
	\   Check Report Data Line    ${rows_list}[${i}]    ${headers}    ${values_list}[${i}]
  