SELENPY_TIMEOUT = "selenpy_timeout"
SELENPY_POLL_DURING_WAITS = "selenpy_poll_during_waits"
SELENPY_OVERRIDE_DRIVER = "selenpy_override_driver"
SELENPY_ELEMENT_CACHING = "selenpy_element_caching"
SELENPY_XPATH_WARNING = "selenpy_xpath_warning"
SELENPY_DEFAULT_TIMEOUT = 5
SELENPY_POLL_DURING_DEFAULT_WAITS = 0.2
SELENPY_OVERRIDE_DRIVER_DEFAULT = True
SELENPY_ELEMENT_CACHING_DEFAULT = True
SELENPY_XPATH_WARNING_DEFAULT = False

REMOTE_HOST_KEY = "remote_host"
PLATFORM_KEY = "platform"
BROWSER_KEY = "browser"
CAPABILITIES_KEY = "capabilities"
OPTIONS_KEY = "options"
ARGUMENTS_KEY = "arguments"
EXECUTABLE_KEY = "executable"

DRIVER_EXECUTION_FOLDER = "drivers"

SELENPY_SYNCSWITCH_TIMEOUT = 180
SELENPY_EMAIL_RECEIVED_TIMEOUT = 300
SELENPY_OBJECT_WAIT = 30
SELENPY_OBJECT_WAIT_PROBE = 10
SELENPY_API_TIMEOUT = 120